In this lesson we will see an introduction to Python libraries we will use during the course, in particular:

* numpy: a library for matrix manipulation and computations
* scipy

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In our exercises we will frequently use arrays to store information: in Python these are usually stored in terms of lists.
Python lists, however, are not computationally efficient. Numpy allows to address this issue through an array data structure.
They can be easily defined from Python lists

In [2]:
l = [1,2,3,4,5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

A numpy array has an associated data type: trying to assign a value that cannot be automatically casted (converted) will result in an error

In [3]:
print(arr.dtype)
arr[0] = 0.1
arr[0] = "Hello world"

int64


ValueError: invalid literal for int() with base 10: 'Hello world'

Numpy array can however generally store data of different types: in this case the base type of the array is 'object'

In [4]:
arr = np.array([0.5, "Hello world", 5], dtype=object)
arr

array([0.5, 'Hello world', 5], dtype=object)

The major advantage of numpy is that it enables easy vector-level operations

In [5]:
l1 = [1,2,3,4,5]
l2 = [2,3,4,5,6]

print(l1 + l2, " <= concatenation")
print(l1*2, " <= replication")

a1 = np.array(l1)
a2 = np.array(l2)

print(a1 + a2, " <= element-wise sum")
print(a1*2, " <= element-wise product")

[1, 2, 3, 4, 5, 2, 3, 4, 5, 6]  <= concatenation
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]  <= replication
[ 3  5  7  9 11]  <= element-wise sum
[ 2  4  6  8 10]  <= element-wise product


We can also directly define numpy vectors using functions. This is especially useful when we need special vectors or matrices

In [6]:
z = np.zeros(5)
print(z)
print()

o = np.ones(5)
print(o)
print()

M = np.eye(5)
print(M)
print()

[0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1.]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



One of the basic elements of a numpy array is its shape: it tells us the number of dimensions and the size of each of them.
E.g. the shape of a 3x2 matrix is (3,2), while the shape of a vector of 5 elements is (5,)

In [7]:
print(z.shape)
print()
print(M.shape)

(5,)

(5, 5)


numpy allows you to easily make linear algebraic computations

In [8]:
print(M.dot(o), "<= Matrix-vector product")
print()
print(o.dot(z), "<= dot-product")

[1. 1. 1. 1. 1.] <= Matrix-vector product

0.0 <= dot-product


numpy usually automatically infers how to perform operations between array with different shapes: this is called *broadcasting*.
In general, numpy replicates one (or both) of the arrays across some dimension, so that the final shapes of the two array match.

In [9]:
np.ones((5,5))*np.array([1,2,3,4,5])

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

However, it doesn't always work.
When operating on two arrays, numpy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when

* they are equal, or

* one of them is 1.

If these conditions are not met, a ValueError: operands could not be broadcast together exception is thrown, indicating that the arrays have incompatible shapes.

See also https://numpy.org/doc/stable/user/basics.broadcasting.html for further info on this

In [10]:
np.ones((5,5)) * np.ones((5,3))

ValueError: operands could not be broadcast together with shapes (5,5) (5,3) 

numpy also provides ways to perform other operations that are useful for several tasks. See the documentation whenever you think you may need some functionality: perhaps it is already implemented!

In [11]:
M = np.ones((5,5))*np.array([1,2,3,4,5])

print(M.T, " <= transpose")
print()
print(np.linalg.inv(M + 0.5*np.eye(5)), " <= inverse")
print()
print(np.linspace(0,1,100), " <= defining a range")

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]]  <= transpose

[[ 1.87096774 -0.25806452 -0.38709677 -0.51612903 -0.64516129]
 [-0.12903226  1.74193548 -0.38709677 -0.51612903 -0.64516129]
 [-0.12903226 -0.25806452  1.61290323 -0.51612903 -0.64516129]
 [-0.12903226 -0.25806452 -0.38709677  1.48387097 -0.64516129]
 [-0.12903226 -0.25806452 -0.38709677 -0.51612903  1.35483871]]  <= inverse

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.5050

So far, we looked at arrays and computations on them... but how can we access and manipulate them?

In [12]:
M = np.eye(5)

print(M[0,0], " <= access a single cell: specificy all indices")
print()
print(M[0,:], " <= access an entire axis range (here, row)")
print()
print(M[:,0], " <= access an entire axis range (here, column)")
print()
print(M[2:4, 2:4], " <= access some range")
print()
print(M[M == 1], " <= access all cells that satisfy some condition")

1.0  <= access a single cell: specificy all indices

[1. 0. 0. 0. 0.]  <= access an entire axis range (here, row)

[1. 0. 0. 0. 0.]  <= access an entire axis range (here, column)

[[1. 0.]
 [0. 1.]]  <= access some range

[1. 1. 1. 1. 1.]  <= access all cells that satisfy some condition


We can also change the shape of an array: this may sometimes be useful when we cannot automatically apply broadcasting

In [13]:
M.reshape((25,))

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

We can also access arrays using for-cycles... but this is not very efficient!

In [15]:
for r in range(M.shape[0]):
    for c in range(M.shape[1]):
        print(M[r,c], " ")
    print()

1.0  
0.0  
0.0  
0.0  
0.0  

0.0  
1.0  
0.0  
0.0  
0.0  

0.0  
0.0  
1.0  
0.0  
0.0  

0.0  
0.0  
0.0  
1.0  
0.0  

0.0  
0.0  
0.0  
0.0  
1.0  

